language: cpp

compiler:
  - gcc
  - clang

before_install:
  - echo $LANG

install:
  - echo $LC_ALL
  
before_script:
  - cd ConsoleApplication1

script:
  - g++ Source.cpp -o hello

branches:
  only:
    - master

notifications:
  email: false
  
deploy:
  provider: releases
  api_key: "adb8cf038f5da16367b2fa8a2fbff5e2548d81db"
  file:
    - "hello.exe"
    - "hello"
  skip_cleanup: true
  on:
    tags: true