language: cpp

compiler:
  - gcc
  - clang

before_install:
  - echo $LANG

install:
  - echo $LC_ALL
  
before_script:
  - cd ConsoleApplication1

script:
  - g++ Source.cpp -o hello

branches:
  only:
    - master

notifications:
  email: false