env:
  global:
   # The next declaration is the encrypted COVERITY_SCAN_TOKEN, created
   #   via the "travis encrypt" command using the project repo's public key
   - secure: "q97U7RzDbnHoRwL9EU9dmNyEdfnpJhG9EGYwAC3EwmMjxYPbX9KuhAAfv4r7Kyq9bAeZpTpqk7fmmyt/fMEul66/Omi5YdDShEzgrtTWPYcsFNKYNMAdARz8kheCJezOV4Y0kIf3wpXox4X8X/5ecTwU2je+he4M+ry5dAfH0gNxK9XxbbOTINxoaLgj/dkdjU3L5mBhHMWZL+BEY7FZtCYX19tGNlcMcuqfz+CuC8mhGMjE5jjMcR5izpH4VyrBKCtwJEGQp0steLzUeE7hkdTeOJlgb71e89fXfngEhxV/3a3jXhV5fJ3FjPE2/twi303/G2T9kgvQBUbZIbRpIEhiA3KYnLaPYNBIv5TbuYahDp3oi1yO2wUTa2taoRO/roVnCKGX0x8unXA42P8r01BYSEdkjnKn+5ldVUe/I3d6Jf7GWILOYmTKd3MWgo5MfvgJEi56qbOoZ9551l1w8M8Zwpt74hL7oq5AhQsD8xu7coGNcOggdyUIqV8IdRh4bAi0DMOS3mRMqb7+ZAkn7A4whn8fZJP1ZgAX7fbK7iTQIQ2796QpTSXMozZHcsNqjVO5bKZsSJ7aqbdA8QizPvqLHCmlBkdnWKNPzTXTQmquFkJQIx7tyiToRLpIgFL6Hl1t1JvjVBlIJy2YFsxGmfLy7kLM53NBcf3OBrqQK2g="
addons:
  coverity_scan:
    project:
      name: "derofim/ConsoleApplication1"
      description: "ConsoleApplication1"
    notification_email: derofim@yandex.ru
    build_command:   "g++ Source.cpp -o hello-$CXX"
    branch_pattern: master
language: cpp
compiler:
- gcc
- clang
before_install:
- echo $LANG
install:
- echo $LC_ALL
before_script:
- cd ConsoleApplication1
script:
- $CXX --version
- if [ "$CXX" = "g++" ]; then export CXX="g++"; fi
- if [ "$CXX" = "clang++" ]; then export CXX="clang++"; fi
- g++ Source.cpp -o hello-$CXX
branches:
  only:
  - master
notifications:
  email: false
before_deploy:
  - ls
  - git config --global user.email "builds@travis-ci.com"
  - git config --global user.name "Travis CI"
  - export GIT_TAG=$TRAVIS_BRANCH-$CXX-v0.1.$TRAVIS_BUILD_NUMBER.$TRAVIS_JOB_NUMBER
  - git tag $GIT_TAG -a -m "TravisCI $TRAVIS_OS_NAME $CXX"
  - git push -q https://1e5c27003d64c633c33c5f68f18875588f849036@github.com/derofim/ConsoleApplication1 --tags
  - git describe --tags --long

deploy:
  provider: releases
  api_key:
    secure: eHsYT4JAmrf8bhZptq2xjenpAwLYpnrBxG/DtmILigHX2+pq+pNKcLgQkfiXCqptYP2vDialtmXY6igP0DprwnXBdncjuth6jPDw0dWC1/A2yD39jEPyL9EiKFxjQA1JmlYCJESR8XV7AjGnPVSf7j9s41jk5u/bJY44/rnCMERi6/Q0Y4bU9X/2ZgRRzoOPXvaT013aFijVcB9hsB8FR90yi4K1oni7/mGS5pbHOcbo6XIgfvz12kgRzmFcjfbPmf4fR9r13I3McCSdgWTlpRF4dPOjo56YjKZW1x5E7orwa6fOvrUtH6rK8Qwv2wQv8MI8tNk3qUa2p4huFtnDDc/f5t1Kew+s3uMOP7tt+l0rEOq8OnNIjjYegiY/4g4sl2efZNqRzO/kTKgd8F6tINIgeRRkr/wWgZqo0ewUN0jvu7NWGs5YbwdlgohCGbkPlQkqSV0vMBYlLt/qP0yWRz6vQ4ZlZJL63itCWTU8MyFhSsRsUmpqG1zyBQ3DvLVxyCamxyQLZAXQZPr/tEZxlVj0EJVU6cYy6yDtiWFDWX4u/MNUGBp3aEQ89u4FdCU4ElCJPTB+0Piii5L1Zt3Bk4gb/AD2DDQVYhXFKrCnXO4oIJLSIfbCbYxYNT4/qaC418Lc1KxJsEPFVUxoxV+aOTSrM0mhMoUqsGWCjOL7edk=
  file: "hello-$CXX"
  skip_cleanup: true
  tags: false
  all_branches: true
  on:
    repo: derofim/ConsoleApplication1
