language: cpp

compiler:
  - gcc
  - clang

before_install:
  - echo $LANG
  - echo $LC_ALL
  - if [ $TRAVIS_OS_NAME == linux ]; then sudo apt-get update && sudo apt-get install -y llvm-3.4 llvm-3.4-dev; fi
  - if [ $TRAVIS_OS_NAME == osx ]; then brew update && brew install llvm35 && brew link --force llvm35; fi
  - rvm use $RVM --install --binary --fuzzy

install:
  - ruby --version
  
before_script:
  - mkdir build
  - cd build ; cmake ..

script:
  - cd build ; make all check

after_success:
  - if [ $TRAVIS_BRANCH == $TRAVIS_TAG ]; then rake deploy; fi

branches:
  only:
    - master

notifications:
  email: false

env:
  - RVM=2.0.0 LANG="en_US.UTF-8"

os:
  - linux
  - osx